adminUser:
  password: vault:cowlglitter/adminUser:password
  username: admin
dashboardAuthID: vault:cowlglitter:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:cowlglitter:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:cowlglitter/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:cowlglitter/prow:hmacToken
